# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180716_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
