# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180716_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'Publish', b'Publish'), (b'private', b'Private')], default=b'draft', max_length=120),
        ),
    ]
