# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180716_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name=b'Post title'),
        ),
    ]
