# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={b'unique': b'This title is not unique. Please try again'}, max_length=240, unique=True, verbose_name=b'Post title'),
        ),
    ]
